#!/bin/bash

main(){
echo 'NOTICE: Bittrex intergration is complete, current and pending bittrex will be added to this report soon. The total reflected at the bottom includes exchanges poloniex, bittrex, and cex.'

echo 'Current *Avaialable* Balances :'
 ./balances.sh
echo "Current *Pending* Balances :"
./get_pending.sh
echo 'Total estimated BTC holdings across Bittrex, Poloniex, and Cex (including all pending orders and not including any pending deposits) :'
total=$(tail -n 1 allbal.log)


echo "$total"
echo "--------------------------------------"
echo 'Total NOT Including ADA (last 100 lines of log):'
total_=$(tail -n 100 v2/new/fine-bal.log)
echo "$total_"
echo '--------------------------------------'
echo "Notice: This email and any attachments contained are confidential. If you recieved this email by mistake, you are legally required to disard this message and notify the sender. Thank you for your compliance."
echo "Automatically generated by vibot"

}

#btc=$(./BAL.sh -b)
main |tee  balance.txt && python ./send_mail -m balance.txt
